Finish Project
yayoamigo/Air-polution-app pull request #2
Opened 2023-01-06 21:18 UTC by yayoamigo

In this pull request I was able to :
-Get metric Data from API.
-Format Data in thunk to be easily used by the app.
-Create dynamic route that changes for each continent clicked.
-Implement searching tool to help users find their target easily.
-Add transitions and styling to meet the required template.
-Add tests .
-Change README to describe the project.

2023-01-06 21:58 UTC, Ismailco requested changes
#### Hi @yayoamigo, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
You did a great job, keep up the good work 👍🏼

![giphy](https://user-images.githubusercontent.com/25227022/169391888-8dd8108f-0d42-4e54-87cc-a3f9fd392dbc.gif)


## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Suggested changes

**I highly suggest using this PR link to request a review and send the project after the review**

_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-06 21:58 UTC, Ismailco commented on README.md
> +
- [ ] The README should contain an "Acknowledgements" section or similar that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/), kindly make sure to give credit to Nelson Sakwa

2023-01-06 21:58 UTC, Ismailco commented on src/Tests/Nav.test.js
> +  expect(component.container).toHaveTextContent('Air polution app');
- [ ] This Test is failing, kindly make sure to fix it so it passes, here is the error message produced 👇🏼

![Screenshot_20230106_223819](https://user-images.githubusercontent.com/25227022/211104404-5d374c47-afee-4f88-a452-161ffdf14ac1.png)

2023-01-06 22:21 UTC, MeqdamAlqudah approved these changes
Hi @yayoamigo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://giphy.com/gifs/approval-approve-13zeE9qQNC5IKk)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 22:21 UTC, MeqdamAlqudah commented on src/App.css
> +  position: relative;
- [Optional ] Please make sure to fix the errors that appear in the console, I think the first one is about the map please try to work on this and understand the map data better, the second one is about the prop type also work on it please.
![image](https://user-images.githubusercontent.com/74744787/211109356-75d5fa5a-1f74-4c25-a167-8b49a1c19344.png)

- [ Optional]  Please try to change the items sizes to match the design 
![image](https://user-images.githubusercontent.com/74744787/211109436-b36e8d67-f732-4732-a0f4-d5f9698bcb0c.png)

2023-01-06 22:21 UTC, MeqdamAlqudah commented on src/App.css
> +  color: #3498db;
- [ Optional] Please use the same color as in the design for items
![image](https://user-images.githubusercontent.com/74744787/211109784-1e87a6ab-a4f3-4d0a-894f-098af0030e5a.png)

2023-01-07 03:21 UTC, merged

2023-01-07 03:28 UTC, yayoamigo commented
Just did, thanks for the feedback. I don't know why but it doesn't appear to be approved in my dashboard @MeqdamAlqudah

2023-01-07 03:37 UTC, zieeco commented
@yayoamigo, Your dashboard would be updated soon.

2023-01-07 03:38 UTC, zieeco commented
@yayoamigo, What does it show on your dashboard?

2023-01-07 03:43 UTC, yayoamigo commented
> @yayoamigo, What does it show on your dashboard?

![rr](https://user-images.githubusercontent.com/24640848/211129727-c6806f1f-2eb7-4b98-9a1d-c0007f9a8717.png)

2023-01-07 03:50 UTC, zieeco reviewed
Hi @yayoamigo ,

 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! tada
 ![](https://camo.githubusercontent.com/63ed5919f2e7113c917b5cc2d5dfdff042758767bb58fef39b9a2b7e21f87a91/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f31337a65453971514e4335494b6b2f67697068792e776562703f6369643d3832613134393362737a37316e7964677232397877626a763132707a7666376f736d3571753466383133616c74357268267269643d67697068792e776562702663743d67)
 
 Cheers and Happy coding!clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-07 03:51 UTC, zieeco commented
@yayoamigo, kindly check your dashboard now and let me know if it has changed with a screenshot of it as you did above. :pray:

2023-01-07 03:56 UTC, yayoamigo commented
> @yayoamigo, kindly check your dashboard now and let me know if it has changed with a screenshot of it as you did above. :pray: 

It works:) thanks

2023-01-07 03:57 UTC, zieeco commented
> > @yayoamigo, kindly check your dashboard now and let me know if it has changed with a screenshot of it as you did above. pray
> 
> It works:) thanks

Please, add the screenshot of it